### PR TITLE
Expose kafka producer, closes #9

### LINKED ISSUE #9: Expose kafkaProducer
Users want to use kafkaProducer in order to publish their messages to an exception topic for the first time.

Instead of they create Kafka producer implementation, we can expose our kafka producer and present them for use.

### PR DESCRIPTION
**Pull request by Abdulsametileri**

### CODE REVIEW

File: pkg/kafka/cronsumer.go [hunk 1]
```diff
@@ -1,10 +1,7 @@
 package kafka
 
 import (
-	"time"
-
 	"github.com/Trendyol/kafka-cronsumer/pkg/logger"
-	"github.com/segmentio/kafka-go/protocol"
```
Comment (Abdulsametileri) [inline pkg/kafka/cronsumer.go:7]: We want to get rid of this dependency at our pkg/kafka directory so we defined new type alias and do some implementation `FromHeaders`, `ToHeaders` as shown above.

File: pkg/kafka/cronsumer_message.go [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+	Partition     int
+	Offset        int64
+	HighWaterMark int64
+	Key           []byte
+	Value         []byte
+	Headers       []Header
+	Time          time.Time
+}
+
+type MessageBuilder struct {
```
Comment (Abdulsametileri) [inline pkg/kafka/cronsumer_message.go:21]: After implementing builder pattern in our `Message` struct, we wanted to extract it new file as `cronsumer_message`. Why we added prefix cronsumer_? It because we want to separate from internal/message.

File: internal/message_header.go [hunk 3]
```diff
@@ -0,0 +1,70 @@
+package internal
```
Comment (Abdulsametileri) [inline internal/message_header.go:1]: We wanted to extract all header related logic to a dedicated file.
